spring:
  application:
    name: newai-notion-backend
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/newai_notion?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 264047
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # MongoDB配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/newai_notion
      database: newai_notion
  
# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.newainotionbackend.entity
  
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: your-email@qq.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # 安全配置
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 文件上传配置
file:
  upload:
    path: uploads
    max-size: 10485760  # 10MB
    allowed-types: jpg,jpeg,png,gif,bmp,webp,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,md,zip,rar,7z

# 应用自定义配置
app:
  # JWT配置
  jwt:
    secret: ${JWT_SECRET:newai-notion-secret-key-2024-very-long-and-secure-for-hs512-algorithm-minimum-512-bits-required}
    access-token-expiration: 86400000  # 24小时
    refresh-token-expiration: 604800000 # 7天
    issuer: newai-notion
  
  # 文件上传配置
  file:
    upload-path: uploads
    upload-dir: uploads
    max-file-size: 10MB
    max-request-size: 50MB
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
      - pdf
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - txt
      - md
      - zip
      - rar
      - 7z
    image-extensions:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
  
  # 邮件配置
  mail:
    from-email: ${MAIL_FROM_EMAIL:noreply@newainotion.com}
    from-name: NewAI Notion
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    encoding: UTF-8
    smtp-auth: true
    smtp-starttls-enable: true
  
  # AI配置
  ai:
    openai-api-key: ${OPENAI_API_KEY:}
    openai-base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    default-model: gpt-3.5-turbo
    max-tokens: 2048
    temperature: 0.7
    request-timeout: 30000
    max-requests-per-minute: 60
    max-requests-per-day: 1000

# 限流配置
rate-limit:
  enabled: true
  requests-per-minute: 60
  requests-per-hour: 1000

# 日志配置
logging:
  level:
    com.example.newainotionbackend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# API文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: NewAI Notion API
    description: AI智能笔记软件后端接口文档
    version: 1.0.0
    contact:
      name: NewAI Notion Team
      email: support@newainotion.com